# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-23 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30)),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('Completed', 'Completed')], default='Pending', max_length=10)),
                ('assignedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignedBy', to=settings.AUTH_USER_MODEL)),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignedTo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskAssignment.TeamList')),
            ],
        ),
        migrations.AddField(
            model_name='tasklist',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskAssignment.TeamList'),
        ),
    ]
